# Generated by Django 3.0.7 on 2025-01-28 09:57

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('role', models.CharField(max_length=12)),
                ('Dp', models.ImageField(blank=True, null=True, upload_to=portfolio.models.getfilename)),
                ('about', models.TextField(max_length=500)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
