# Generated by Django 4.2 on 2025-01-29 11:42

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('img', models.ImageField(blank=True, null=True, upload_to=portfolio.models.getfilename)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('duration', models.DateField()),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('img', models.ImageField(blank=True, null=True, upload_to=portfolio.models.getfilename)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=portfolio.models.getfilename)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=portfolio.models.getfilename)),
                ('dec', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='git',
            field=models.URLField(default='https://github.com/example'),
        ),
        migrations.AddField(
            model_name='profile',
            name='index_email',
            field=models.EmailField(default='example@example.com', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='index_git',
            field=models.URLField(default='https://github.com/example', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='index_linkedin',
            field=models.URLField(default='dk'),
        ),
        migrations.AddField(
            model_name='profile',
            name='index_phone',
            field=models.CharField(default='phone', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(default='https://www.linkedin.com/in/example/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='+91 1234567890', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
