# Generated by Django 4.2 on 2025-01-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_certificate_education_project_skills_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='index_linkedin',
            field=models.CharField(default='dk', max_length=200),
        ),
    ]
