# Generated by Django 4.2 on 2025-01-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_profile_index_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='id_url',
            field=models.URLField(default='https://www.linkedin.com/in/example/'),
        ),
    ]
