# Generated by Django 4.2 on 2025-01-31 06:50

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_profile_user_alter_certificate_img_alter_profile_dp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.getfilename_icon, validators=[portfolio.models.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='work',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.getfilename_icon, validators=[portfolio.models.validate_file_type]),
        ),
    ]
