# Generated by Django 4.2 on 2025-01-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_skills_icon_alter_work_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='duration',
            field=models.CharField(max_length=150),
        ),
    ]
