# Generated by Django 4.2 on 2025-01-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_education_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='percentage',
            field=models.CharField(max_length=150),
        ),
    ]
